#!/usr/bin/env ruby
#
# radbeacon-flasher
#
# USAGE
#
# On a mac you should not need to pass any options in to flash the default
# firmware to the beacon. The firmware will be automatically downloaded. Use
# the `-w` option to "watch" for the beacon to be plugged in and continue
# flashing beacon.
#
# For full usage run with `--help` option:
#
#   radbeacon-flasher --help
#
# PREREQUISITES
#
# This script requires both serhex and dfu-util.
#
# serhex can be installed from source:
#   https://github.com/RadiusNetworks/serhex
#
# dfu-util can be found in most package managers:
#   brew install dfu-util         ; # On Mac
#   sudo apt-get install dfu-util ; # On Ubuntu
#
require "ostruct"
require "net/http"
require "uri"
require 'csv'
#
# Default Settings
#
options = OpenStruct.new
options.version = "3.2.3"
options.watch = false
options.port = "/dev/tty.usbmodem1"

################################################################################

require 'fileutils'
require 'net/http'

class FirmwareError < StandardError; end

class FirmwareFile
  DEFAULT_PREFIX = "radbeacon-usb-"
  SIZE=360492

  def initialize(firmware_name)
    firmware_name = mangle_name(firmware_name)

    @filename = "#{firmware_name}.hex"
    @filepath = File.expand_path "~/.radbeacon/firmware/#{@filename}"
  end

  def mangle_name(firmware_name)

    # handle radbeacon-g shorthand,
    # ex: `radbeacon-flasher --version g-0-2-9`
    if firmware_name =~ /^radbeacon-usb-g-/
      firmware_name.gsub!('usb-g-', 'g-')
    end
    # Replace dots for dashes
    firmware_name.gsub! ".", "-"

    firmware_name
  end

  def path
    fetch unless File.exist? @filepath
    raise FirmwareError, "File size mismatch, may be corrupted" unless valid?
    @filepath
  end

  def valid?
    File.size(@filepath) == SIZE
  end

  def fetch
    puts "Downloading Firmware #{@filename}"
    url = "https://s3.amazonaws.com/downloads.radiusnetworks.com/43D9DC92-4AB7-4C9E-ABF2-EEB3A496EBDF/#{@filename}"
    FileUtils.mkdir_p File.dirname(@filepath)

    uri = URI.parse(url)
    Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new(uri.request_uri)

      response = http.request request # Net::HTTPResponse object
      if(response.code != "200")
        puts "ERROR: Unable to fetch #{url}"
        exit 1
      end
      File.write(@filepath, response.body)
    end
  end
end

class ConfigFile

  def initialize(config_file_name)
    @configfilepath = File.expand_path "#{config_file_name}"
    rows = CSV.parse(File.open(config_file_name)).to_a
    cols = rows.shift
    @confighashed = Array.new
    collection = rows.collect do |row|  
        @confighashed.push(Hash[*cols.zip(row).flatten])
    end 
  end
  
  def path
    @configfilepath
  end
  
  def hashed
    @confighashed
  end
end

class DFUer
  V21_DFU = "aa"
  V20_DFU = "30"
  V32_DFU = "142751fc3e204ffc8c468474f7d9e52b"
  BLUGIGA_DFU = "0001090001"
  NICE_DFU_V2 = "0530303030"
  NICE_DFU_V3 = "05303030303030303000"
  attr_reader :port
  def initialize(port)
    @port = port
  end

  def apply
    if File.exist? port
      [V21_DFU, V20_DFU, BLUGIGA_DFU, V32_DFU, NICE_DFU_V2, NICE_DFU_V3].each do |cmd|
        dfu_cmd(cmd, port)
        sleep 0.5
        return true if dfu_mode?
      end
    end

    return true if dfu_mode?

    sleep 2 # WTF

    dfu_mode?
  end

  private

  def dfu_mode?
    `dfu-util -l`.include? "Found DFU: [2458:fffe]"
  end

  def dfu_cmd(cmd, port)
    `serhex #{port} #{cmd} 2>&1 > /dev/null`
  end
end

class Flasher
  attr_reader :dir, :name
  def initialize(path)
    @dir = File.dirname(path)
    @name = File.basename(path)
  end

  def flash
    # looks like dfu-util has to execute in the same directory as the firmware image
    # try without sudo first, if that fails use sudo.
    Dir.chdir(dir) do |path|
      precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
      cmd = "#{precmd}dfu-util -d 2458:fffe -D #{name} -R"

      # using system so we get the output of dfu-util
      print "\033[34m"
      system(cmd)
      print "\033[0m"
    end
    $?.success?
  end
end

class ProgressSpinner
  def self.tick
    @chars ||= %w{| / - \\}
    print "\b#{(@chars.rotate!).last}"
  end
end

################################################################################

require 'optparse'
OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename $0} [options]"

  opts.on("-VVERSION", "--version=VERSION", "Firmware Version (#{options.version})") do |ver|
    options.version = ver
  end
  opts.on("-FFIRMWARE", "--firmware=firmware", "Firmware Name (n/a) - will override any version setting") do |fw|
    options.firmware = fw
  end
    opts.on("-CCONFIGFILE", "--configfile=configfile", "Config File Name ") do |cf|
    options.configfile = cf
  end
end.parse!

# Check for system commands needed by this script
%w{dfu-util serhex}.each do |cmd|
  unless system("which #{cmd} > /dev/null 2>&1")
    STDERR.puts "ERROR: Missing #{cmd} command"
    exit 1
  end
end

def wait_for_remove_beacon(port)
  loop do
    # TODO: Refactor so we are not duplicating this util specific code
    break unless `dfu-util -l`.include?("Found DFU: [2458:fffe]")
    sleep 0.1
  end
  puts
end

def wait_for_beacon(port)
  loop do
    break if File.exist?(port)
    # If a dongle is stuck in DFU mode, it's ok to flash it.
    break if `dfu-util -l`.include?("Found DFU: [2458:fffe]")
    sleep 0.1
    ProgressSpinner.tick
  end
  puts
end

require 'pathname'
START_SOUND   = Pathname("/System/Library/Sounds/Purr.aiff")
SUCCESS_SOUND = Pathname("/System/Library/Sounds/Frog.aiff")
FAILURE_SOUND = Pathname("/System/Library/Sounds/Sosumi.aiff")

def play_sound(file)
  `afplay #{file}`
end

def notify_start
  play_sound START_SOUND if START_SOUND.exist?
end

def notify_success
  system "osascript -e 'display notification \"Success\" with title \"RadBeacon Flasher\"'"
  play_sound SUCCESS_SOUND if SUCCESS_SOUND.exist?
  puts
  puts "Success!"
end

def notify_failure
  play_sound FAILURE_SOUND if FAILURE_SOUND.exist?
  puts
  puts "Failure!"
end

def run(options)
#  puts "Using port #{options.port}"
#  puts "WARNING: #{options.port} does not exist" unless File.exist? options.port
#  firmware_file_name = options.firmware || "#{FirmwareFile::DEFAULT_PREFIX}#{options.version}"
#  file = FirmwareFile.new(firmware_file_name)
#  puts "Using fimware #{file.path}"
#  puts "Going into DFU mode..."
#  dfu = DFUer.new options.port
  notify_start

#  if (dfu.apply)
#    puts "DFU Success, flashing..."
#    flasher = Flasher.new(file.path)
#    if flasher.flash
#      notify_success
#    else
#      notify_failure
#    end
#  else
#    notify_failure
#    STDERR.puts "ERROR: DFU failed!"
#  end
end

def GenerateAndAppendCRC ( lineData)
    lineHex = [lineData].first.chars.each_slice(2).map(&:join)
    crcVal = 0
    lineHex.each do|c|
        crcVal = crcVal + c.to_i(16) 
    end
    crcVal = 0 - (crcVal & 0xFF)
    crcStr = '%02X' % ( crcVal & 0xFF )
    ":" + lineData + crcStr.downcase + "\n"
end

def modifyFirmwareLine(firmware, line, start, string)
    lineData = firmware[line]
    linePrefix = lineData[1..start-1]
    linePostfix = lineData[start + string.length..40]
    firmware[line] = GenerateAndAppendCRC( linePrefix + string + linePostfix )
    puts("line " + line.to_s)
    puts("lineData " + lineData)
    puts("linePrefix " + linePrefix)
    puts("linePostfix " + linePostfix)
    puts(firmware[line])
end

trap(:INT) do
  puts "\n\n    kthxbye"
  exit 0
end



# begin main program execution

# get firmware file
firmware_file_name = options.firmware || "#{FirmwareFile::DEFAULT_PREFIX}#{options.version}"
firmwarefile = FirmwareFile.new(firmware_file_name)

puts "Using firmware #{firmwarefile.path}"

# get config file
config_file_name = options.configfile
configfile = ConfigFile.new(config_file_name)
#puts "Using config file #{configfile.path}"
#puts "here's what I think I have for csv #{configfile.hashed}"

configfile.hashed.each_index do |i|
    hash = configfile.hashed[i]
    
    puts("\n")
    
    if (hash.key?("mac"))
        puts("                     MAC:" + hash["mac"].upcase)
    end
    if (hash.key?("pin"))
        puts("                     PIN:" + hash["pin"].upcase)
    end
    if (hash.key?("name"))
        puts("                    Name:" + hash["name"])
    end
    if ((hash.key?("interval")) and (hash.key?("txpower")) and (hash.key?("modes")))
        puts("            Beacon Modes:" + hash["modes"].upcase)
        puts("                Interval:" + hash["interval"].upcase)
        puts("                TX Power:" + hash["txpower"].upcase)
    end
    if (hash.key?("ibeacon"))
        puts("  iBeacon/AltBeacon Data:" + hash["ibeacon"].upcase)
    end
    if (hash.key?("eddystoneuid"))
        puts("      Eddystone UID Data:" + hash["eddystoneuid"].upcase)
    end
    if (hash.key?("eddystoneurl"))
        puts("      Eddystone URL Data:" + hash["eddystoneurl"].upcase)
    end
    puts
    
    # get fresh copy of firmware
    firmware = File.readlines(firmwarefile.path)

    # configure PIN
    if (hash.key?("pin"))
        encodedPin = hash["pin"].unpack('H*').first
        puts encodedPin
        puts "\n"
        puts encodedPin[0..15]
        puts "\n"
        modifyFirmwareLine(firmware, 7074, 33, encodedPin[0..7])
        modifyFirmwareLine(firmware, 7075, 21, encodedPin[8..15])
    end
    
    # create temporary file firmware file
    tmp_firmware_file = "/tmp/rbcfg-" + firmware_file_name + "-" + i.to_s
    File.open(tmp_firmware_file + ".hex", 'w') { |file| file.write("#{firmware.join}") }
    
    # convert firmware hex file to bin file
    precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
    cmd = "#{precmd}gobjcopy -I ihex " + tmp_firmware_file + ".hex -O binary " + tmp_firmware_file + "-prestrip.bin"
    puts cmd
    system(cmd)
    cmd = "#{precmd}dd bs=1024 if=" + tmp_firmware_file + "-prestrip.bin of=" + tmp_firmware_file + ".bin skip=4 count=122"
    puts cmd
    system(cmd)
    cmd = "#{precmd}dfu-util -d 2458:fffe -D " + tmp_firmware_file + ".bin"
    puts cmd
    system(cmd)


    
    #
    
    
end



# get csv file

#loop do
#  if options.watch
#    print "Please insert beacon (ctrl-c to cancel)  "
#    wait_for_beacon(options.port)
#  end

# run(options)

# break unless options.watch

# wait_for_remove_beacon options.port
#end
