#!/usr/bin/env ruby
#
# radbeacon-flasher
#
# USAGE
#
# On a mac you should not need to pass any options in to flash the default
# firmware to the beacon. The firmware will be automatically downloaded. Use
# the `-w` option to "watch" for the beacon to be plugged in and continue
# flashing beacon.
#
# For full usage run with `--help` option:
#
#   radbeacon-flasher --help
#
# PREREQUISITES
#
# This script requires both serhex and dfu-util.
#
# serhex can be installed from source:
#   https://github.com/RadiusNetworks/serhex
#
# dfu-util can be found in most package managers:
#   brew install dfu-util         ; # On Mac
#   sudo apt-get install dfu-util ; # On Ubuntu
#
require "ostruct"
require "net/http"
require "uri"
require 'csv'
require 'yaml'
require 'curses'
#
# Default Settings
#
options = OpenStruct.new
options.version = "3.2.3"
options.watch = false
options.port = "/dev/tty.usbmodem1"

################################################################################

require 'fileutils'
require 'net/http'

class FirmwareError < StandardError; end

class FirmwareFile
  DEFAULT_PREFIX = "radbeacon-usb-"
  SIZE=360492

  def initialize(firmware_name)
    @firmware_name = mangle_name(firmware_name)

    @filename = "#{firmware_name}.hex"
    @filepath = File.expand_path "~/.radbeacon/firmware/#{@filename}"
  end

  def mangle_name(firmware_name)

    # handle radbeacon-g shorthand,
    # ex: `radbeacon-flasher --version g-0-2-9`
    if firmware_name =~ /^radbeacon-usb-g-/
      firmware_name.gsub!('usb-g-', 'g-')
    end
    # Replace dots for dashes
    firmware_name.gsub! ".", "-"

    firmware_name
  end
  
  def name
    @firmware_name
  end
  
  
  def path
    fetch unless File.exist? @filepath
    raise FirmwareError, "File size mismatch, may be corrupted" unless valid?
    @filepath
  end

  def valid?
    File.size(@filepath) == SIZE
  end

  def fetch
    puts "Downloading Firmware #{@filename}"
    url = "https://s3.amazonaws.com/downloads.radiusnetworks.com/43D9DC92-4AB7-4C9E-ABF2-EEB3A496EBDF/#{@filename}"
    FileUtils.mkdir_p File.dirname(@filepath)

    uri = URI.parse(url)
    Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new(uri.request_uri)

      response = http.request request # Net::HTTPResponse object
      if(response.code != "200")
        puts "ERROR: Unable to fetch #{url}"
        exit 1
      end
      File.write(@filepath, response.body)
    end
  end
end

class BinaryFile
  SIZE=124928
  TMPDIR="/tmp"

  def initialize(firmware)
    prestripped_name = convert2bin(firmware)
    @filename = strip(prestripped_name)
    @filepath = File.expand_path "#{TMPDIR}/#{@filename}"
  end
  
  def fetch
    puts "Downloading Firmware #{@filename}"
    url = "https://s3.amazonaws.com/downloads.radiusnetworks.com/43D9DC92-4AB7-4C9E-ABF2-EEB3A496EBDF/#{@filename}"
    FileUtils.mkdir_p File.dirname(@filepath)

    uri = URI.parse(url)
    Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
      request = Net::HTTP::Get.new(uri.request_uri)

      response = http.request request # Net::HTTPResponse object
      if(response.code != "200")
        puts "ERROR: Unable to fetch #{url}"
        exit 1
      end
      File.write(@filepath, response.body)
    end
  end
  
  def convert2bin(firmware)
    # convert firmware hex file to bin file
    prestripped_name = firmware.name + "-prestrip.bin"
    precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
    cmd = "#{precmd}gobjcopy -I ihex " + firmware.path + " -O binary " + TMPDIR + "/" + prestripped_name 
    system("#{cmd} 2>/dev/null 1>/dev/null")
    prestripped_name
  end
  
  def strip(prestripped_name)
    # convert firmware hex file to bin file
    stripped_name = prestripped_name.split('-prestrip').first + ".bin"
    precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
    cmd = "#{precmd}dd bs=1024 if=" + TMPDIR + "/" + prestripped_name + " of=" + TMPDIR + "/" + stripped_name + " skip=4 count=122"
    system("#{cmd} 2>/dev/null 1>/dev/null")
    stripped_name
  end

  
  def name
    @firmware_name
  end
  
  
  def path
    fetch unless File.exist? @filepath
    raise FirmwareError, "File size mismatch, may be corrupted" unless valid?
    @filepath
  end

  def valid?
    File.size(@filepath) == SIZE
  end
  
end


class ConfigFile
  def initialize(config_file_name)
    @configfilepath = File.expand_path "#{config_file_name}"
    csv_text = File.read(config_file_name)
#    puts csv_text.squeeze("\r\n").gsub(/(\r\n)+/, "\r\n")
    rows = CSV.parse(csv_text.squeeze("\r\n").gsub(/(\r\n)+/, "\r\n")).to_a
    cols = rows.shift
    @confighashed = Array.new
    collection = rows.collect do |row|  
        @confighashed.push(Hash[*cols.zip(row).flatten])
    end 
  end
  
  def path
    @configfilepath
  end
  
  def hashed
    @confighashed
  end
end



class DFUer
  V21_DFU = "aa"
  V20_DFU = "30"
  V32_DFU = "142751fc3e204ffc8c468474f7d9e52b"
  BLUGIGA_DFU = "0001090001"
  NICE_DFU_V2 = "0530303030"
  NICE_DFU_V3 = "05303030303030303000"
  attr_reader :port
  def initialize(port)
    @port = port
  end

  def apply
    if File.exist? port
      [V21_DFU, V20_DFU, BLUGIGA_DFU, V32_DFU, NICE_DFU_V2, NICE_DFU_V3].each do |cmd|
        dfu_cmd(cmd, port)
        sleep 0.5
        return true if dfu_mode?
      end
    end

    return true if dfu_mode?

    sleep 2 # WTF

    dfu_mode?
  end

  private

  def dfu_mode?
    `dfu-util -l`.include? "Found DFU: [2458:fffe]"
  end

  def dfu_cmd(cmd, port)
    `serhex #{port} #{cmd} 2>&1 > /dev/null`
  end
end

class Flasher
  attr_reader :dir, :name
  def initialize(path)
    @dir = File.dirname(path)
    @name = File.basename(path)
  end

  def flash
    # looks like dfu-util has to execute in the same directory as the firmware image
    # try without sudo first, if that fails use sudo.
    Dir.chdir(dir) do |path|
      precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
      cmd = "#{precmd}dfu-util -d 2458:fffe -D #{name} 2>1"
      # using system so we get the output of dfu-util
#      print "\033[34m"
#      system(cmd)
      output = `#{cmd}`
#      print "\033[0m"
      if ($?.success?)
        puts "......................................................SUCCESS!"
      else
        puts "......................................................FAILED!"
        puts output
        exit
      end
    end
    $?.success?
  end
end

class ProgressSpinner
  def self.tick
    @chars ||= %w{| / - \\}
    print "\b#{(@chars.rotate!).last}"
  end
end

################################################################################

require 'optparse'
OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename $0} [options]"
  opts.on("-w", "--watch", "Run forever and watch for new beacons") do
    options.watch = true
  end
  opts.on("-r", "--resume", "Resume on last attempted configuration CSV File entry") do
    options.resume = true
  end
  opts.on("-cCSVFILE[:XX]", "--configure=csvfile[:XX]", "Configuration CSV File (#{options.csvfile})") do |csvfile|
    configInput = csvfile.split(':')
    options.csvfile = configInput[0]
    if (configInput.length == 2)
        options.resumeNumber = configInput[1]
    else
        options.resumeNumber = 1
    end
  end
  opts.on("-pPORT", "--port=port", "Logical Port (#{options.port})") do |port|
    options.port = port
  end
  opts.on("-VVERSION", "--version=VERSION", "Firmware Version (#{options.version})") do |ver|
    options.version = ver
  end
  opts.on("-FFIRMWARE", "--firmware=firmware", "Firmware Name (n/a) - will override any version setting") do |fw|
    options.firmware = fw
  end
opts.on("-lLABELPRINTER", "--labelprinter=printer", "Label Printer (#{options.printer})") do |printer|
    options.printer = printer
  end
end.parse!

# Check for system commands needed by this script
%w{dfu-util serhex}.each do |cmd|
  unless system("which #{cmd} > /dev/null 2>&1")
    STDERR.puts "ERROR: Missing #{cmd} command"
    exit 1
  end
end

def move_cursor_back_one
  print "\f"
end

def wait_for_remove_beacon(port)
  loop do
    # TODO: Refactor so we are not duplicating this util specific code
    break unless `dfu-util -l 2>/dev/null`.include?("Found DFU: [2458:fffe]")
    sleep 0.1
    ProgressSpinner.tick
  end
end

def wait_for_beacon(port)
  loop do
    break if File.exist?(port)
    # If a dongle is stuck in DFU mode, it's ok to flash it.
    break if `dfu-util -l`.include?("Found DFU: [2458:fffe]")
    sleep 0.1
    ProgressSpinner.tick
  end
end

def wait_for_remove_configured_beacon(port)
  loop do
    break unless File.exist?(port)
    sleep 0.1
    ProgressSpinner.tick
  end
end

require 'pathname'
NEXT_SOUND    = Pathname("/System/Library/Sounds/Submarine.aiff")
START_SOUND   = Pathname("/System/Library/Sounds/Purr.aiff")
SUCCESS_SOUND = Pathname("/System/Library/Sounds/Frog.aiff")
FAILURE_SOUND = Pathname("/System/Library/Sounds/Sosumi.aiff")
FINISH_SOUND  = Pathname("/System/Library/Sounds/Glass.aiff")

def play_sound(file)
  `afplay #{file}`
end

def notify_start
  play_sound START_SOUND if START_SOUND.exist?
end

def notify_success
  system "osascript -e 'display notification \"Success\" with title \"RadBeacon Flasher\"'"
  play_sound SUCCESS_SOUND if SUCCESS_SOUND.exist?
  puts
  puts "SUCCESS!"
  puts
end

def notify_failure
  play_sound FAILURE_SOUND if FAILURE_SOUND.exist?
  puts
  puts "FAILURE!"
end


def notifyConfigDetails(firmware, hash, file, entry, count, printer)
    puts
    puts("=========================================================================")
    puts("   Firmware File: " + firmware)
    puts("   Label Printer: " + printer)
    puts("     Config File: " + file)
    puts("    Config Entry: " + entry.to_s + " of " + count.to_s)
    puts("=========================================================================")
    if (hash.key?("name"))
        puts("                   Name: " + hash["name"])
    end
    if (hash.key?("ib-enable"))
        puts("         iBeacon Enable: " + hash["ib-enable"])
    end
    if (hash.key?("ab-enable"))
        puts("       altBeacon Enable: " + hash["ab-enable"])
    end
    if (hash.key?("euid-enable"))
        puts("   Eddystone UID Enable: " + hash["euid-enable"])
    end
    if (hash.key?("eurl-enable"))
        puts("   Eddystone URL Enable: " + hash["eurl-enable"])
    end
    if (hash.key?("ia-uuid") and hash.key?("ia-major") and hash.key?("ia-minor") and hash.key?("ia-power"))
        puts(" iBeacon/AltBeacon Data: " + hash["ia-uuid"].upcase + " " + hash["ia-major"] + " " + hash["ia-minor"] + " " + hash["ia-power"])
    end
    if (hash.key?("euid-namespace") and hash.key?("euid-instance") and hash.key?("euid-power"))
        puts("     Eddystone UID Data: " + hash["euid-namespace"].upcase + " " + hash["euid-instance"] + " " + hash["euid-power"])
    end
    if (hash.key?("eurl-url") and hash.key?("eurl-power"))
        puts("     Eddystone URL Data: " + hash["eurl-url"] + " " + hash["eurl-power"])
    end
    if (hash.key?("rate"))
        puts("                   Rate: " + hash["rate"].upcase)
    end
    if (hash.key?("txpower"))
        puts("               TX Power: " + hash["txpower"].upcase)
    end
    if (hash.key?("pin"))
        puts("                    PIN: " + hash["pin"].upcase)
    end
    puts("=========================================================================")
end



def flash(binary, port)
#  puts "WARNING: #{port} does not exist" unless File.exist? port
  print "Flashing..."
  dfu = DFUer.new port
  notify_start

  if (dfu.apply)
    flasher = Flasher.new(binary.path)
    if flasher.flash
      return true
    else
      notify_failure
      return false
    end
  else
    notify_failure
    return false
  end
end


def encodeurl(url)

  
  schemes = [
    "http://www.",
    "https://www.",
    "http://",
    "https://",
    ]

  extensions = [
    ".com/", ".org/", ".edu/", ".net/", ".info/", ".biz/", ".gov/",
    ".com", ".org", ".edu", ".net", ".info", ".biz", ".gov",
  ]
  
  data = ""
  
  s = 0
  i = 0
  e = 0
  l = 0
  for scheme in schemes
    if url.start_with?(scheme)
      data = "%02X" % s
      i += scheme.length
      break
    end
    s += 1
  end
  
  if s == scheme.length
    puts
    puts "ERROR: Invalid Eddystone URL scheme"
    exit
  end
  
  while i < url.length
    if url[i] == '.'
      for expansion in extensions
        if url[i..-1].start_with?(expansion)
          data << "%02X" % e
          i += expansion.length
          break
        end
        e += 1
      end
      if url[i] == '.'
        data << "2E"
        i += 1
      end
    else
      data << "%02X" % url[i].ord
      i += 1
    end
    l += 1
  end
  
  if l > 18
    puts
    puts "ERROR: Invalid Eddystone URL length #{l}"
    exit
  end
  
  return data
end

def getTxPowerSetting(db)

  settings = {"-23"=>0,"-21"=>1,"-20"=>2,"-18"=>3,"-16"=>4,"-14"=>5,"-12"=>6,"-11"=>7,"-8"=>8,"-7"=>9,"-5"=>10,"-4"=>11,"-2"=>12,"-1"=>13,"+0"=>14,"+3"=>15,"0"=>14,"3"=>15}
  if settings.key?(db)
    return settings[db]
  else
    puts
    puts "ERROR: #{db} is not a valid tx power value"
    exit
  end
end

def validate(hash, entry)

    # validate name
    if (hash.key?("name"))
        if (hash["name"].length > 24)
            puts
            puts("ERROR: Entry " + entry.to_s + ", Name exceeds 24 characters")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", name value is missing")
        exit
    end
    
    # validate enable
    if (!hash.key?("ib-enable"))
        puts
        puts("ERROR: Entry " + entry.to_s + ", ib-enable is missing")
        exit
    end
    if (!hash.key?("ab-enable"))
        puts
        puts("ERROR: Entry " + entry.to_s + ", ab-enable is missing")
        exit
    end
    if (!hash.key?("euid-enable"))
        puts
        puts("ERROR: Entry " + entry.to_s + ", euid-enable is missing")
        exit
    end
    if (!hash.key?("eurl-enable"))
        puts
        puts("ERROR: Entry " + entry.to_s + ", eurl-enable is missing")
        exit
    end
        
    # validate ibeacon and altbeacon
    if (hash.key?("ia-uuid"))
        if ( hash["ia-uuid"].to_s !~ /\A[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}\z/ )
            puts
            puts("ERROR: Entry " + entry.to_s + ", ia-uuid is invalid")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", ia-uuid is missing")
        exit
    end
    if (hash.key?("ia-major"))
        if ( hash["ia-major"].to_i < 0 || hash["ia-major"].to_i > 65535 )
            puts
            puts("ERROR: Entry " + entry.to_s + ", ia-major is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", ia-major is missing")
        exit
    end
    if (hash.key?("ia-minor"))
        if ( hash["ia-minor"].to_i < 0 || hash["ia-minor"].to_i > 65535 )
            puts
            puts("ERROR: Entry " + entry.to_s + ", ia-minor is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", ia-minor is missing")
        exit
    end
    if (hash.key?("ia-power"))
        if ( hash["ia-power"].to_i > -1 || hash["ia-power"].to_i < -127 )
            puts
            puts("ERROR: Entry " + entry.to_s + ", ia-power is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", ia-power is missing")
        exit
    end
    
    # validate eddystone uid
    if (hash.key?("euid-namespace"))
        if ( hash["euid-namespace"].to_s !~ /\A[A-Fa-f0-9]{20}\z/ )
            puts
            puts("ERROR: Entry " + entry.to_s + ", euid-namespace is invalid")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", euid-namespace is missing")
        exit
    end
    if (hash.key?("euid-instance"))
        if ( hash["euid-instance"].to_s !~ /\A[A-Fa-f0-9]{12}\z/ )
            puts
            puts("ERROR: Entry " + entry.to_s + ", euid-instance is invalid")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", euid-instance is missing")
        exit
    end
    if (hash.key?("euid-power"))
        if ( hash["euid-power"].to_i > -1 || hash["euid-power"].to_i < -127 )
            puts
            puts("ERROR: Entry " + entry.to_s + ", euid-power is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", euid-power is missing")
        exit
    end
    
    # validate eddystone url
    if (hash.key?("eurl-url"))
        urldata = encodeurl(hash["eurl-url"])
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", eurl-url is missing")
        exit
    end
    if (hash.key?("eurl-power"))
        if ( hash["eurl-power"].to_i > -1 || hash["eurl-power"].to_i < -127 )
            puts
            puts("ERROR: Entry " + entry.to_s + ", eurl-power is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", eurl-power is missing")
        exit
    end
    
    # validate rate
    if (hash.key?("rate"))
        if ( hash["rate"].to_i < 1 || hash["eurl-power"].to_i > 10)
            puts
            puts("ERROR: Entry " + entry.to_s + ", rate is out of range")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", rate is missing")
        exit
    end
    
    # validate txpower
    if (hash.key?("txpower"))
        txpower = getTxPowerSetting(hash["txpower"])
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", txpower is missing")
        exit
    end
    
    #validate pin
    if (hash.key?("pin"))
        if ( hash["pin"].length != 8)
            puts
            puts("ERROR: Entry " + entry.to_s + ", pin length is invalid")
            exit
        end
    else
        puts
        puts("ERROR: Entry " + entry.to_s + ", pin is missing")
        exit
    end
    
end
  
  
def configure(hash, port, printer)
#    puts "WARNING: #{port} does not exist" unless File.exist? port
    
    precmd = RUBY_PLATFORM.include?("darwin") ? "" : "sudo "
    
    # name
    name = hash["name"]

    # modes
    modes = 0
    if (hash["ib-enable"].to_i > 0)
    modes += 1
    end
    if (hash["ab-enable"].to_i > 0)
    modes += 2
    end
    if (hash["euid-enable"].to_i > 0)
    modes += 4
    end
    if (hash["eurl-enable"].to_i > 0)
    modes += 8
    end

    #ibeacon frame
    prefix = "0201061aff4c000215"
    postfix = "00"
    frame = prefix + hash["ia-uuid"].tr('-', '') + "%04X"%hash["ia-major"] + "%04X"%hash["ia-minor"] + "%02X"%(256 + hash["ia-power"].to_i) + postfix
    ibeacon_frame = frame.upcase

    #altbeacon frame
    prefix = "0201061bff1801beac"
    postfix = "00"
    frame = prefix + hash["ia-uuid"].tr('-', '') + "%04X"%hash["ia-major"] + "%04X"%hash["ia-minor"] + "%02X"%(256 + hash["ia-power"].to_i) + postfix
    altbeacon_frame = frame.upcase

    #eddystone uid frame
    prefix = "0201060303aafe1716aafe00"
    postfix = "0000"
    frame = prefix + "%02X"%(256 + hash["euid-power"].to_i) + hash["euid-namespace"] + hash["euid-instance"] + postfix
    euid_frame = frame.upcase

    #eddystone url frame
    urldata = encodeurl(hash["eurl-url"])
    pdulength = '%02X' % ( urldata.length/2 + 5 )
    padding = "00000000000000000000000000000000000000"
    prefix = "0201060303aafe#{pdulength}16aafe10"
    postfix = padding[0,padding.length - urldata.length - 2]
    frame = prefix + "%02X"%(256 + hash["eurl-power"].to_i) + urldata + postfix
    eurl_frame = frame.upcase

    #rate
    rate = hash["rate"].to_i * 10

    #txpower
    txpower = getTxPowerSetting(hash["txpower"])

    #pin
    pin = hash["pin"]
    
    #label
    label1 = hash.key?("label1") ? hash["label1"] : ""
    label2 = hash.key?("label2") ? hash["label2"] : ""
    label3 = hash.key?("label3") ? hash["label3"] : ""
    label4 = hash.key?("label4") ? hash["label4"] : ""
    label5 = hash.key?("label5") ? hash["label5"] : ""
    label6 = hash.key?("label6") ? hash["label6"] : ""
    
    #configure
    print "\nConfiguring..."
    
    # configure name
    if ($?.success? and hash.key?("name"))
        cmd = "#{precmd}rbcom -P00000000 name '#{name}'"
        print(".")
        cmdoutput = `#{cmd}`
    end
    # configure modes
    if ($?.success? and hash.key?("ib-enable") and hash.key?("ab-enable") and hash.key?("euid-enable") and hash.key?("eurl-enable"))

        cmd = "#{precmd}rbcom -P00000000 bctype #{modes}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure ibeacon frame
    if ($?.success? and hash.key?("ia-uuid") and hash.key?("ia-major") and hash.key?("ia-minor") and hash.key?("ia-power"))

        cmd = "#{precmd}rbcom -P00000000 frame0 #{ibeacon_frame}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
     # configure altbeacon frame
    if ($?.success? and hash.key?("ia-uuid") and hash.key?("ia-major") and hash.key?("ia-minor") and hash.key?("ia-power"))
        cmd = "#{precmd}rbcom -P00000000 frame1 #{altbeacon_frame}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure eddystone uid frame
    if ($?.success? and hash.key?("euid-namespace") and hash.key?("euid-instance") and hash.key?("euid-power"))
        cmd = "#{precmd}rbcom -P00000000 frame2 #{euid_frame}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure eddystone url frame
    if ($?.success? and hash.key?("eurl-url") and hash.key?("eurl-power"))
        cmd = "#{precmd}rbcom -P00000000 frame3 #{eurl_frame}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure rate
    if ($?.success? and hash.key?("rate"))
        cmd = "#{precmd}rbcom -P00000000 advrate #{rate}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure txpower
    if ($?.success? and hash.key?("txpower"))
        cmd = "#{precmd}rbcom -P00000000 txpwr #{txpower}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    
    # configure pin
    if ($?.success? and hash.key?("pin"))
        cmd = "#{precmd}rbcom -P00000000 chgpin #{pin}"
        print(".")
        cmdoutput = `#{cmd}`
    end
    if ($?.success?)
        puts "..........................................SUCCESS!"
    else
        puts "..........................................FAILED!"
        puts cmdoutput
        exit
    end

    # verify
    print "Verifying..."
    cmd = "#{precmd}rbcom dump getinfo"
    cmdoutput = `#{cmd}`
    ymloutput = YAML.load(cmdoutput)
    
    # verify name
    if ($?.success? and hash.key?("name") )
#        if (name.eql? ymloutput["device"]["name"])
#            print(".")
#        else
#            puts "FAILED!"
#            puts "Name:"
#            puts "Expected: #{name}XX"
#            puts "Received: #{ymloutput["device"]["name"]}XX"
#            exit
#        end
    end
    # verify modes
    if ($?.success? and hash.key?("ib-enable") and hash.key?("ab-enable") and hash.key?("euid-enable") and hash.key?("eurl-enable"))
        if (modes.eql? ymloutput["ops"]["bctype"])
            print(".")
        else
            puts "FAILED!"
            puts "Modes:"
            puts "Expected: #{modes}"
            puts "Received: #{ymloutput["ops"]["bctype"]}"
            exit
        end
    end
    # verify ibeacon frame
    if ($?.success? and hash.key?("ia-uuid") and hash.key?("ia-major") and hash.key?("ia-minor") and hash.key?("ia-power"))
        if (ibeacon_frame.eql? ymloutput["frame0"]["frame"].delete(":").upcase)
            print(".")
        else
            puts "FAILED!"
            puts "iBeacon Frame:"
            puts "Expected: #{ibeacon_frame}"
            puts "Received: #{ymloutput["frame0"]["frame"].delete(":").upcase}"
            exit
        end
    end
    # verify altbeacon frame
    if ($?.success? and hash.key?("ia-uuid") and hash.key?("ia-major") and hash.key?("ia-minor") and hash.key?("ia-power"))
        if (altbeacon_frame.eql? ymloutput["frame1"]["frame"].delete(":").upcase)
            print(".")
        else
            puts "FAILED!"
            puts "AltBeacon Frame:"
            puts "Expected: #{altbeacon_frame}"
            puts "Received: #{ymloutput["frame1"]["frame"].delete(":").upcase}"
            exit
        end
    end
    # verify eddystone uid frame
    if ($?.success? and hash.key?("euid-namespace") and hash.key?("euid-instance") and hash.key?("euid-power"))
        if (euid_frame.eql? ymloutput["frame2"]["frame"].delete(":").upcase)
            print(".")
        else
            puts "FAILED!"
            puts "Eddystone UID Frame:"
            puts "Expected: #{euid_frame}"
            puts "Received: #{ymloutput["frame2"]["frame"].delete(":").upcase}"
            exit
        end
    end
    # verify eddystone url frame
    if ($?.success? and hash.key?("eurl-url") and hash.key?("eurl-power"))
        if (eurl_frame.eql? ymloutput["frame3"]["frame"].delete(":").upcase)
            print(".")
        else
            puts "FAILED!"
            puts "Eddystone URL Frame:"
            puts "Expected: #{eurl_frame}"
            puts "Received: #{ymloutput["frame3"]["frame"].delete(":").upcase}"
            exit
        end
    end
    # verify rate
    if ($?.success? and hash.key?("rate"))
        if (rate.eql? ymloutput["ops"]["advrate"])
            print(".")
        else
            puts "FAILED!"
            puts "Rate:"
            puts "Expected: #{rate}"
            puts "Received: #{ymloutput["ops"]["advrate"]}"
            exit
        end
    end
    # verify twpower
    if ($?.success? and hash.key?("txpower"))
        if (txpower.eql? ymloutput["ops"]["txpwr"])
            print(".")
        else
            puts "FAILED!"
            puts "Tx Power:"
            puts "Expected: #{txpower}"
            puts "Received: #{ymloutput["ops"]["txpwr"]}"
            exit
        end
    end
    # verify PIN
    # to do this, I'm going to reset the name with the configured PIN value
    if ($?.success? and hash.key?("pin") )
        cmd = "#{precmd}rbcom -P#{pin} name '#{ymloutput["device"]["name"]}'"
        cmdoutput = `#{cmd}`
        if ($?.success?)
            print(".")
        else
            puts "FAILED!"
            puts "PIN:"
            puts "Expected: #{pin}"
            puts "Received: Error testing a name write withthis PIN"
            exit
        end
    end
    
    if ($?.success?)
        puts "............................................SUCCESS!"
    else
        puts "............................................FAILED!"
        puts cmdoutput
        exit
    end
    
    # label
    # verify name
    if (hash.key?("label1") or hash.key?("label2") or hash.key?("label3") or hash.key?("label4") or hash.key?("label5") or hash.key?("label6"))
        
        label = "#{label1}\n#{label2}\n#{label3}\n#{label4}\n#{label5}\n#{label6}"
        padding = "                                            "
        display_label = " -----------------------------------------------\n" +
        "| " + label1.to_s + padding[0,padding.length - label1.to_s.length] + " |\n" +
        "| " + label2.to_s + padding[0,padding.length - label2.to_s.length] + " |\n" +
        "| " + label3.to_s + padding[0,padding.length - label3.to_s.length] + " |\n" +
        "| " + label4.to_s + padding[0,padding.length - label4.to_s.length] + " |\n" +
        "| " + label5.to_s + padding[0,padding.length - label5.to_s.length] + " |\n" +
        "| " + label6.to_s + padding[0,padding.length - label6.to_s.length] + " |\n" +
                        " -----------------------------------------------\n"
        puts "Printing label..."
        puts display_label
        print_label(label, printer)
    else
        puts "Skipping label print: No label data present"
    end
    
    return $?.success?
    
end


def print_label(label, printer)
    `lpr -P #{printer} -o landscape -o PageSize=Custom.1x3.5in -o cpi=14 -o lpi=7 -# 1 <<< "#{label}"`
end


trap(:INT) do
  puts "\n\n    kthxbye"
  exit 0
end


# main

firmware_file_name = options.firmware || "#{FirmwareFile::DEFAULT_PREFIX}#{options.version}"
firmwarefile = FirmwareFile.new(firmware_file_name)

printer = options.printer ||  "Brother_QL_700"
    
if options.csvfile
  if options.resume
    options.resumeNumber = File.read('./resume.txt')
  end
  resumeNumber = options.resumeNumber.to_i
  if (resumeNumber < 1)
    resumeNumber = 1
  end
  File.open('./resume.txt', 'w') { |file| file.write(resumeNumber) }
  configfile = ConfigFile.new(options.csvfile)
  configfile.hashed.each_index do |i|
    if (i == resumeNumber - 1)
    
        hash = configfile.hashed[i]
        validate(hash, resumeNumber)
        notifyConfigDetails(firmware_file_name, hash, options.csvfile, resumeNumber.to_s, configfile.hashed.length, printer)
    
        loop do
#          system("clear")
          puts "Please insert beacon to flash (ctrl-c to cancel)  "
          play_sound NEXT_SOUND if NEXT_SOUND.exist?
          wait_for_beacon(options.port)
      
          binary = BinaryFile.new(firmwarefile)
          break if (flash(binary, options.port))
          puts "Press ENTER to restart (ctrl-c to cancel)  "
          input = gets
        end
      
        play_sound NEXT_SOUND if NEXT_SOUND.exist?
    
        print "Please REMOVE AND REINSERT BEACON to configure (ctrl-c to cancel)  "
        wait_for_remove_beacon(options.port)
        wait_for_beacon(options.port)
    
#        hash = configfile.hashed[i]
#        validate(hash, resumeNumber)
#        notifyConfigDetails(hash, options.csvfile, resumeNumber.to_s)
        play_sound START_SOUND if START_SOUND.exist?
 
        status = configure(hash, options.port, printer)
        if (status)
          play_sound FINISH_SOUND if FINISH_SOUND.exist?
          print "Please REMOVE CONFIGURED BEACON (ctrl-c to cancel)  "
          wait_for_remove_configured_beacon(options.port)
          puts
          puts "Press ENTER to continue to next beacon  (ctrl-c to cancel)  "
          input = gets
          resumeNumber += 1
          File.open('./resume.txt', 'w') { |file| file.write(resumeNumber) }
        else
          play_sound FINISH_SOUND if FINISH_SOUND.exist?
          puts
          print "FAILED! Please remove beacon and check CSV values or command line options "
          wait_for_remove_configured_beacon(options.port)
          puts
          puts
          exit
        end
    end
  end
  play_sound NEXT_SOUND if NEXT_SOUND.exist?
else if options.watch
  loop do
    puts
    print "Please insert beacon (ctrl-c to cancel)  "
    play_sound NEXT_SOUND if NEXT_SOUND.exist?
    wait_for_beacon(options.port)
    binary = BinaryFile.new(firmwarefile)
    flash(binary, options.port)
    print "Please remove beacon (ctrl-c to cancel)  "
    wait_for_remove_beacon options.port
  end
  play_sound NEXT_SOUND if NEXT_SOUND.exist?
else
  puts
  print "Please insert beacon (ctrl-c to cancel)  "
  play_sound NEXT_SOUND if NEXT_SOUND.exist?
  wait_for_beacon(options.port)
  binary = BinaryFile.new(firmwarefile)
  flash(binary, options.port)
  print "Please remove beacon (ctrl-c to cancel)  "
  wait_for_remove_beacon options.port
  puts
end

end
